### ISSUE TITLE
same error in jarvis, ive tried everything!!!!

### ISSUE THREAD

**Issue by maadmackz** [crackallcode/AI-Assistant-#1]
Traceback (most recent call last):
  File "C:\Users\macst\PycharmProjects\pythonProject1\slave.py", line 19, in get_adio
    audio = r.listen(source)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\macst\PycharmProjects\pythonProject1\venv\Lib\site-packages\speech_recognition\__init__.py", line 465, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\macst\PycharmProjects\pythonProject1\slave.py", line 40, in <module>
    get_adio()
  File "C:\Users\macst\PycharmProjects\pythonProject1\slave.py", line 18, in get_adio
    with sr.Microphone(device_index=1) as source:
  File "C:\Users\macst\PycharmProjects\pythonProject1\venv\Lib\site-packages\speech_recognition\__init__.py", line 189, in __exit__
    self.stream.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

Process finished with exit code 1

**Comment by theaskews08** [comment]
The error message you're encountering is happening because your code is trying to use an audio source outside of its proper context, which is indicated by the AssertionError. This error suggests that the audio source (in this case, the microphone) must be initialized and used within a with statement context to ensure proper setup and teardown. The AttributeError that follows is a result of the first error, where because the audio source was not correctly set up, attempting to close a non-existent (NoneType) stream leads to an exception.

Let's address this issue methodically, ensuring thoroughness and accuracy for direct application in your IDE:

Step 1: Verify Correct Use of with Statement
Ensure that your get_adio() function (assuming a typo, and you meant get_audio()) uses the with statement correctly when accessing the microphone. The correct structure looks like this:

import speech_recognition as sr

def get_audio():
    # Initialize recognizer class (for recognizing the speech)
    r = sr.Recognizer()
    
    # Use the microphone as source for input. Here, we're specifying device_index=1
    with sr.Microphone(device_index=1) as source:
        print("Listening...")
        # Listen for the first phrase and extract it into audio data
        audio = r.listen(source)
        
        try:
            # Recognize speech using Google Web Speech API
            text = r.recognize_google(audio)
            print("You said: {}".format(text))
        except Exception as e:
            print("Error : " + str(e))

# Call the function
get_audio()

Dependencies Installed: Verify that all necessary packages are installed. You need SpeechRecognition and PyAudio for microphone access. You can install these using pip:

bash
Copy code
pip install SpeechRecognition pyaudio
